// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWuhDKqwwbxzAV_yNABeCdC9A053YT790',
    appId: '1:867741449655:web:920ec197f2eb7d7b86bc32',
    messagingSenderId: '867741449655',
    projectId: 'my-bloc-auth',
    authDomain: 'my-bloc-auth.firebaseapp.com',
    storageBucket: 'my-bloc-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPqv-PGUX_12gL-MNshG-l8iYki6AvgkE',
    appId: '1:867741449655:android:49ac69ad7c19cba386bc32',
    messagingSenderId: '867741449655',
    projectId: 'my-bloc-auth',
    storageBucket: 'my-bloc-auth.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvjk6Lc9NKxUzD9tg49xl7BnFhIWM_Qnw',
    appId: '1:867741449655:ios:d3431720fe759d3a86bc32',
    messagingSenderId: '867741449655',
    projectId: 'my-bloc-auth',
    storageBucket: 'my-bloc-auth.firebasestorage.app',
    androidClientId: '867741449655-1r8fs850ehrh9p5r867slqpjqngqca91.apps.googleusercontent.com',
    iosClientId: '867741449655-lf22v6d1mfb6er1i4q3s4mvs5dk8qjpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseBlocAuth',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvjk6Lc9NKxUzD9tg49xl7BnFhIWM_Qnw',
    appId: '1:867741449655:ios:d3431720fe759d3a86bc32',
    messagingSenderId: '867741449655',
    projectId: 'my-bloc-auth',
    storageBucket: 'my-bloc-auth.firebasestorage.app',
    androidClientId: '867741449655-1r8fs850ehrh9p5r867slqpjqngqca91.apps.googleusercontent.com',
    iosClientId: '867741449655-lf22v6d1mfb6er1i4q3s4mvs5dk8qjpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseBlocAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiCbHlbj_Oeg_Olv0i62-sosBErVSGVp0',
    appId: '1:867741449655:web:bde4d2919a577afb86bc32',
    messagingSenderId: '867741449655',
    projectId: 'my-bloc-auth',
    authDomain: 'my-bloc-auth.firebaseapp.com',
    storageBucket: 'my-bloc-auth.firebasestorage.app',
  );

}